import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [text, setText] = useState('')
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <button onClick={async ()=>{
          const body = {text: "Write a 200-250 word essay about a personal experience in an untraditional learning space."}
          const generateText = await fetch("http://localhost:3000/api/generateText", {
            method: "POST",
            body: JSON.stringify(body),
            headers: {
              "Content-Type": "application/json",
              // 'Content-Type': 'application/x-www-form-urlencoded',
            },
          })
          const json = await generateText.json()
          console.log(json)
          setText(json.response)
        }}>
          Generate Text
        </button>
        {text?<p>{text}</p>:null}
      </div>
    </>
  )
}
