import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [text, setText] = useState('')
  const [value, setValue] = useState('')
  const [loading, setLoading] = useState(false)
  return (
    <div className="w-screen h-screen justify-center items-center flex">
      <Head>
        <title>Essay Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-screen h-screen justify-center items-center flex">
        <div className="w-screen h-screen justify-center items-center flex flex-col">
          <textarea value={value} onChange={(e)=>{
            setValue(e.target.value)
          }}/>
           <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-2" disabled={!value || value.length===0 || loading} onClick={async ()=>{
            const body = {text: value}
            setLoading(true)
            const generateText = await fetch("http://localhost:3000/api/generateText", {
              method: "POST",
              body: JSON.stringify(body),
              headers: {
                "Content-Type": "application/json"
              },
            })
            setLoading(false)
            const json = await generateText.json()
            console.log(json)
            setText(json.response)
          }}>
            Generate Text
          </button>
          {loading?<p>Loading...</p>:null}
          {text?<p>{text}</p>:null}
        </div>
      </div>
    </div>
  )
}
